language: ruby
rvm:
  - 2.2.2
script:
  - bin/rails db:migrate RAILS_ENV=test
  - bin/rails test
notifications:
  email:
    recipients:
      - joshua.muheim@access-for-all.ch
    on_failure: change
    on_success: change